package com.tecknobit.nova.ui.theme.tagstheme.bug
import androidx.compose.ui.graphics.Color

/**
 * Set of default bug light theme colors
 */
val md_theme_light_primary = Color(0xFFB4252B)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDAD7)
val md_theme_light_onPrimaryContainer = Color(0xFF410004)
val md_theme_light_secondary = Color(0xFF775654)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDAD7)
val md_theme_light_onSecondaryContainer = Color(0xFF2C1514)
val md_theme_light_tertiary = Color(0xFF735B2E)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDEA7)
val md_theme_light_onTertiaryContainer = Color(0xFF271900)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF201A1A)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF201A1A)
val md_theme_light_surfaceVariant = Color(0xFFF5DDDB)
val md_theme_light_onSurfaceVariant = Color(0xFF534342)
val md_theme_light_outline = Color(0xFF857371)
val md_theme_light_inverseOnSurface = Color(0xFFFBEEEC)
val md_theme_light_inverseSurface = Color(0xFF362F2E)
val md_theme_light_inversePrimary = Color(0xFFFFB3AE)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFFB4252B)
val md_theme_light_outlineVariant = Color(0xFFD8C2C0)
val md_theme_light_scrim = Color(0xFF000000)
